apiVersion: v1
kind: Pod
metadata:
  name: pod-nodepool1
  labels:
    name: pod-nodepool1
spec:
  nodeName: aks-nodepool1-15879888-vmss000000
  containers:
  - name: pod-nodepool1
    image: nginx
    resources:
      limits:
        memory: "28Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
